services:
  postgres:
    image: postgres
    container_name: postgres
    networks:
      - my-network
    ports:
      - 5436:5432
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: back-end
    build: .
    image: back-end
    networks:
      - my-network
    ports:
      - 80:5000
    depends_on:
      - postgres
    env_file:
      - .env

networks:
  my-network:
    name: my-network
    driver: bridge

volumes:
  postgres-volume:
